<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AttributeTableSeeder extends Seeder
{
  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run()
  {
    DB::table('attributes')->delete();
    $now = Carbon::now();
    $query = DB::table('attributes')->insert(
      [
        [
          'id'                  => '1',
          'code'                => 'sku',
          'name'                => 'SKU',
          'type'                => 'text',
          'validation'          => NULL,
          'position'            => '1',
          'is_required'         => '1',
          'is_unique'           => '1',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '2',
          'code'                => 'name',
          'name'                => '名称',
          'type'                => 'text',
          'validation'          => NULL,
          'position'            => '3',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '1',
        ], [
          'id'                  => '3',
          'code'                => 'url_key',
          'name'                => 'URL Key',
          'type'                => 'text',
          'validation'          => NULL,
          'position'            => '4',
          'is_required'         => '1',
          'is_unique'           => '1',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '4',
          'code'                => 'tax_category_id',
          'name'                => '税种',
          'type'                => 'select',
          'validation'          => NULL,
          'position'            => '5',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '5',
          'code'                => 'new',
          'name'                => '新品',
          'type'                => 'boolean',
          'validation'          => NULL,
          'position'            => '6',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '6',
          'code'                => 'featured',
          'name'                => '特色',
          'type'                => 'boolean',
          'validation'          => NULL,
          'position'            => '7',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '7',
          'code'                => 'visible_individually',
          'name'                => '单独可见',
          'type'                => 'boolean',
          'validation'          => NULL,
          'position'            => '9',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '8',
          'code'                => 'status',
          'name'                => '状态',
          'type'                => 'boolean',
          'validation'          => NULL,
          'position'            => '10',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '9',
          'code'                => 'short_description',
          'name'                => '简短描述',
          'type'                => 'textarea',
          'validation'          => NULL,
          'position'            => '11',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '10',
          'code'                => 'description',
          'name'                => '描述',
          'type'                => 'textarea',
          'validation'          => NULL,
          'position'            => '12',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '1',
        ], [
          'id'                  => '11',
          'code'                => 'price',
          'name'                => '价格',
          'type'                => 'price',
          'validation'          => 'decimal',
          'position'            => '13',
          'is_required'         => '1',
          'is_unique'           => '0',

          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '1',
        ], [
          'id'                  => '12',
          'code'                => 'cost',
          'name'                => '费用',
          'type'                => 'price',
          'validation'          => 'decimal',
          'position'            => '14',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '13',
          'code'                => 'special_price',
          'name'                => '特价',
          'type'                => 'price',
          'validation'          => 'decimal',
          'position'            => '15',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '14',
          'code'                => 'special_price_from',
          'name'                => '特价开始时间',
          'type'                => 'date',
          'validation'          => NULL,
          'position'            => '16',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '15',
          'code'                => 'special_price_to',
          'name'                => '特价结束时间',
          'type'                => 'date',
          'validation'          => NULL,
          'position'            => '17',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '16',
          'code'                => 'meta_title',
          'name'                => 'Meta标题',
          'type'                => 'textarea',
          'validation'          => NULL,
          'position'            => '18',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '17',
          'code'                => 'meta_keywords',
          'name'                => 'Meta关键词',
          'type'                => 'textarea',
          'validation'          => NULL,
          'position'            => '20',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '18',
          'code'                => 'meta_description',
          'name'                => 'Meta描述',
          'type'                => 'textarea',
          'validation'          => NULL,
          'position'            => '21',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '19',
          'code'                => 'length',
          'name'                => '长度',
          'type'                => 'text',
          'validation'          => 'decimal',
          'position'            => '22',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '20',
          'code'                => 'width',
          'name'                => '宽度',
          'type'                => 'text',
          'validation'          => 'decimal',
          'position'            => '23',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '21',
          'code'                => 'height',
          'name'                => '高度',
          'type'                => 'text',
          'validation'          => 'decimal',
          'position'            => '24',
          'is_required'         => '0',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '22',
          'code'                => 'weight',
          'name'                => '重量',
          'type'                => 'text',
          'validation'          => 'decimal',
          'position'            => '25',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '23',
          'code'                => 'color',
          'name'                => '颜色',
          'type'                => 'select',
          'validation'          => NULL,
          'position'            => '26',
          'is_required'         => '0',
          'is_unique'           => '0',

          'is_configurable'     => '1',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '24',
          'code'                => 'size',
          'name'                => '尺寸',
          'type'                => 'select',
          'validation'          => NULL,
          'position'            => '27',
          'is_required'         => '0',
          'is_unique'           => '0',

          'is_configurable'     => '1',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '25',
          'code'                => 'brand',
          'name'                => '品牌',
          'type'                => 'select',
          'validation'          => NULL,
          'position'            => '28',
          'is_required'         => '0',
          'is_unique'           => '0',

          'is_configurable'     => '0',
          'is_user_defined'     => '1',
          'is_visible_on_front' => '1',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '26',
          'code'                => 'guest_checkout',
          'name'                => '游客结账',
          'type'                => 'boolean',
          'validation'          => NULL,
          'position'            => '8',
          'is_required'         => '1',
          'is_unique'           => '0',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ], [
          'id'                  => '27',
          'code'                => 'product_number',
          'name'                => '产品编号',
          'type'                => 'text',
          'validation'          => NULL,
          'position'            => '2',
          'is_required'         => '0',
          'is_unique'           => '1',
          'is_configurable'     => '0',
          'is_user_defined'     => '0',
          'is_visible_on_front' => '0',
          'created_at'          => $now,
          'updated_at'          => $now,
          'is_comparable'       => '0',
        ]
      ]
    );
  }
}
